source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

#pod 'Result'
#pod 'Async', git: 'https://github.com/duemunk/Async.git', tag: '1.4'
#pod 'Async', :git => 'https://github.com/duemunk/Async.git', :commit => 'abe23c18d8d3a708a325b5db10231388e1ca5b88'
pod 'XCGLogger'
#pod 'SVProgressHUD'
#pod 'GPUImage'
#pod 'Alamofire'
#pod 'Kingfisher'
#pod 'RealmSwift'
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'R.swift'
#pod 'Cartography'
#pod 'PromiseKit'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
