// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import UIKit

struct R {
  static func validate() {
    storyboard.main.validateImages()
    storyboard.main.validateViewControllers()
  }
  
  struct file {
    static var cartfile: NSURL? { return NSBundle.mainBundle().URLForResource("Cartfile", withExtension: "") }
    static var lookupPng: NSURL? { return NSBundle.mainBundle().URLForResource("lookup", withExtension: "png") }
    static var lookup_amatorkaPng: NSURL? { return NSBundle.mainBundle().URLForResource("lookup_amatorka", withExtension: "png") }
    static var lookup_miss_etikatePng: NSURL? { return NSBundle.mainBundle().URLForResource("lookup_miss_etikate", withExtension: "png") }
    static var lookup_soft_elegance_1Png: NSURL? { return NSBundle.mainBundle().URLForResource("lookup_soft_elegance_1", withExtension: "png") }
    static var lookup_soft_elegance_2Png: NSURL? { return NSBundle.mainBundle().URLForResource("lookup_soft_elegance_2", withExtension: "png") }
  }
  
  struct font {
    
  }
  
  struct image {
    static var actionButton: UIImage? { return UIImage(named: "action-button") }
    static var appLogo: UIImage? { return UIImage(named: "app-logo") }
    static var bar: UIImage? { return UIImage(named: "bar") }
    static var check: UIImage? { return UIImage(named: "check") }
    static var chevron_left: UIImage? { return UIImage(named: "chevron_left") }
    static var circleCheck: UIImage? { return UIImage(named: "circle-check") }
    static var close: UIImage? { return UIImage(named: "close") }
    static var filterButton: UIImage? { return UIImage(named: "filter-button") }
    static var infoBarItem: UIImage? { return UIImage(named: "info-bar-item") }
    static var lookup: UIImage? { return UIImage(named: "lookup") }
    static var lookup_amatorka: UIImage? { return UIImage(named: "lookup_amatorka") }
    static var lookup_miss_etikate: UIImage? { return UIImage(named: "lookup_miss_etikate") }
    static var lookup_soft_elegance_1: UIImage? { return UIImage(named: "lookup_soft_elegance_1") }
    static var lookup_soft_elegance_2: UIImage? { return UIImage(named: "lookup_soft_elegance_2") }
    static var maximumTrack: UIImage? { return UIImage(named: "maximum-track") }
    static var minimumTrack: UIImage? { return UIImage(named: "minimum-track") }
    static var minimum_track: UIImage? { return UIImage(named: "minimum_track") }
    static var pauseButton: UIImage? { return UIImage(named: "pause-button") }
    static var playButton: UIImage? { return UIImage(named: "play-button") }
    static var reRecordButton: UIImage? { return UIImage(named: "re-record-button") }
    static var recStartButton: UIImage? { return UIImage(named: "rec-start-button") }
    static var recStopButton: UIImage? { return UIImage(named: "rec-stop-button") }
    static var recordBarItem: UIImage? { return UIImage(named: "record-bar-item") }
    static var settingsBarItem: UIImage? { return UIImage(named: "settings-bar-item") }
    static var songButton: UIImage? { return UIImage(named: "song-button") }
    static var thumbTrack: UIImage? { return UIImage(named: "thumb-track") }
    static var watchBarItem: UIImage? { return UIImage(named: "watch-bar-item") }
  }
  
  struct nib {
    static var launchScreen: _R.nib._LaunchScreen { return _R.nib._LaunchScreen() }
  }
  
  struct reuseIdentifier {
    static var songTableViewCell: ReuseIdentifier<Dubbidson.SongTableViewCell> { return ReuseIdentifier(identifier: "SongTableViewCell") }
    static var suggestionTableViewCell: ReuseIdentifier<Dubbidson.SuggestionTableViewCell> { return ReuseIdentifier(identifier: "SuggestionTableViewCell") }
    static var videoViewCell: ReuseIdentifier<Dubbidson.VideoViewCell> { return ReuseIdentifier(identifier: "VideoViewCell") }
  }
  
  struct segue {
    static var recordVideo: String { return "recordVideo" }
    static var selectFilter: String { return "selectFilter" }
    static var selectSong: String { return "selectSong" }
    static var watchVideo: String { return "watchVideo" }
  }
  
  struct storyboard {
    struct main {
      static var initialViewController: UITabBarController? { return instance.instantiateInitialViewController() as? UITabBarController }
      static var instance: UIStoryboard { return UIStoryboard(name: "Main", bundle: nil) }
      static var suggestionsViewController: Dubbidson.SuggestionsViewController? { return instance.instantiateViewControllerWithIdentifier("SuggestionsViewController") as? Dubbidson.SuggestionsViewController }
      
      static func validateImages() {
        assert(UIImage(named: "song-button") != nil, "[R.swift] Image named 'song-button' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "tv") != nil, "[R.swift] Image named 'tv' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "info-bar-item") != nil, "[R.swift] Image named 'info-bar-item' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "rec-start-button") != nil, "[R.swift] Image named 'rec-start-button' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "filter-button") != nil, "[R.swift] Image named 'filter-button' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "pause-button") != nil, "[R.swift] Image named 'pause-button' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "record-bar-item") != nil, "[R.swift] Image named 'record-bar-item' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "chevron_left") != nil, "[R.swift] Image named 'chevron_left' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "watch-bar-item") != nil, "[R.swift] Image named 'watch-bar-item' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "close") != nil, "[R.swift] Image named 'close' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "play-button") != nil, "[R.swift] Image named 'play-button' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "action-button") != nil, "[R.swift] Image named 'action-button' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "check") != nil, "[R.swift] Image named 'check' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "re-record-button") != nil, "[R.swift] Image named 're-record-button' is used in storyboard 'Main', but couldn't be loaded.")
      }
      
      static func validateViewControllers() {
        assert(suggestionsViewController != nil, "[R.swift] ViewController with identifier 'suggestionsViewController' could not be loaded from storyboard 'Main' as 'Dubbidson.SuggestionsViewController'.")
      }
    }
  }
}

struct _R {
  struct nib {
    struct _LaunchScreen: NibResource {
      var instance: UINib { return UINib.init(nibName: "LaunchScreen", bundle: nil) }
      var name: String { return "LaunchScreen" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
  }
}

struct ReuseIdentifier<T>: CustomStringConvertible {
  let identifier: String
  
  var description: String { return identifier }
}

protocol NibResource {
  var instance: UINib { get }
  var name: String { get }
}

protocol Reusable {
  typealias T
  
  var reuseIdentifier: ReuseIdentifier<T> { get }
}

extension UITableView {
  func dequeueReusableCellWithIdentifier<T : UITableViewCell>(identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath?) -> T? {
    if let indexPath = indexPath {
      return dequeueReusableCellWithIdentifier(identifier.identifier, forIndexPath: indexPath) as? T
    }
    return dequeueReusableCellWithIdentifier(identifier.identifier) as? T
  }
  
  func dequeueReusableCellWithIdentifier<T : UITableViewCell>(identifier: ReuseIdentifier<T>) -> T? {
    return dequeueReusableCellWithIdentifier(identifier.identifier) as? T
  }
  
  func dequeueReusableHeaderFooterViewWithIdentifier<T : UITableViewHeaderFooterView>(identifier: ReuseIdentifier<T>) -> T? {
    return dequeueReusableHeaderFooterViewWithIdentifier(identifier.identifier) as? T
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UITableViewCell>(nibResource: T) {
    registerNib(nibResource.instance, forCellReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibForHeaderFooterView<T: NibResource where T: Reusable, T.T: UIView>(nibResource: T) {
    registerNib(nibResource.instance, forHeaderFooterViewReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UITableViewCell>(nibResources: [T]) {
    nibResources.forEach(registerNib)
  }
}

extension UICollectionView {
  func dequeueReusableCellWithReuseIdentifier<T: UICollectionViewCell>(identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath) -> T? {
    return dequeueReusableCellWithReuseIdentifier(identifier.identifier, forIndexPath: indexPath) as? T
  }
  
  func dequeueReusableSupplementaryViewOfKind<T: UICollectionReusableView>(elementKind: String, withReuseIdentifier identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath) -> T? {
    return dequeueReusableSupplementaryViewOfKind(elementKind, withReuseIdentifier: identifier.identifier, forIndexPath: indexPath) as? T
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UICollectionViewCell>(nibResource: T) {
    registerNib(nibResource.instance, forCellWithReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UICollectionReusableView>(nibResource: T, forSupplementaryViewOfKind kind: String) {
    registerNib(nibResource.instance, forSupplementaryViewOfKind: kind, withReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UICollectionViewCell>(nibResources: [T]) {
    nibResources.forEach(registerNib)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UICollectionReusableView>(nibResources: [T], forSupplementaryViewOfKind kind: String) {
    nibResources.forEach { self.registerNib($0, forSupplementaryViewOfKind: kind) }
  }
}

extension UIViewController {
  convenience init(nib: NibResource) {
    self.init(nibName: nib.name, bundle: nil)
  }
}